In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df1 = pd.read_csv("data_csv_Thang/air_pollution.csv")

In [22]:
df1.head()

,ParentLocationCode,SpatialDim,Dim1,Value,NumericValue,Date,IndicatorCode
0,EMR,ARE,SEX_BTSX,7 [5-9],7.26606,2022-08-26T09:40:54+02:00,AIR_10
1,AFR,ZMB,SEX_FMLE,266 [78-492],266.23209,2022-08-26T09:41:03+02:00,AIR_10
2,WPR,AUS,SEX_BTSX,1 [0-1],0.72083,2022-08-26T09:40:54+02:00,AIR_10
3,AFR,COG,SEX_FMLE,249 [43-528],249.31205,2022-08-26T09:40:55+02:00,AIR_10
4,AMR,ATG,SEX_FMLE,5 [1-11],4.77712,2022-08-26T09:40:54+02:00,AIR_10

In [23]:
df1.tail()

,ParentLocationCode,SpatialDim,Dim1,Value,NumericValue,Date,IndicatorCode
491071,AMR,VEN,RESIDENCEAREATYPE_CITY,17.66 [13.32-23.12],17.66130,2022-08-12T09:00:45+02:00,SDGPM25
491072,WPR,FJI,RESIDENCEAREATYPE_TOWN,8.05 [4.89-12.98],8.05264,2022-08-12T08:59:27+02:00,SDGPM25
491073,AFR,AGO,RESIDENCEAREATYPE_TOWN,24.33 [5.75-71.32],24.33109,2022-08-12T08:58:50+02:00,SDGPM25
491074,EMR,KWT,RESIDENCEAREATYPE_URB,68.79 [59.52-79.71],68.78559,2022-08-12T08:59:49+02:00,SDGPM25
491075,EUR,AUT,RESIDENCEAREATYPE_RUR,11.03 [10.66-11.43],11.02630,2022-08-12T08:58:56+02:00,SDGPM25

In [24]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491076 entries, 0 to 491075
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ParentLocationCode  437864 non-null  object
 1   SpatialDim          491076 non-null  object
 2   Dim1                490882 non-null  object
 3   Value               491076 non-null  object
 4   NumericValue        490896 non-null  float64
 5   Date                491076 non-null  object
 6   IndicatorCode       491076 non-null  object
dtypes: float64(1), object(6)
memory usage: 26.2+ MB

In [25]:
'''
 0   ParentLocationCode  :object  :Mã khu vực
 1   SpatialDim          :object  :Không gian địa lý (mã quốc gia hoặc vùng)
 2   Dim1                :object  :Chiều để phân loại phụ 
 3   Value               :object  :Giá trị gốc của WHO (để kiểm tra dữ liệu thô)
 4   NumericValue        :float64 :Phiên bản số hóa của Value (tính toán, thống kê, vẽ)
 5   Date                :object  :Năm hoặc khoảng thời gian
 6   IndicatorCode       :object  :Mã chỉ số y tế
'''

'\n 0   ParentLocationCode  :object  :Mã khu vực\n 1   SpatialDim          :object  :Không gian địa lý (mã quốc gia hoặc vùng)\n 2   Dim1                :object  :Chiều để phân loại phụ \n 3   Value               :object  :Giá trị gốc của WHO (để kiểm tra dữ liệu thô)\n 4   NumericValue        :float64 :Phiên bản số hóa của Value (tính toán, thống kê, vẽ)\n 5   Date                :object  :Năm hoặc khoảng thời gian\n 6   IndicatorCode       :object  :Mã chỉ số y tế\n'

In [26]:
df1.describe()

       NumericValue
count  4.908960e+05
mean   1.146485e+05
std    1.871427e+06
min    0.000000e+00
25%    7.391068e+00
50%    9.427950e+01
75%    1.735496e+03
max    2.110137e+08

In [27]:
df1.describe(include='object')

,ParentLocationCode,SpatialDim,Dim1,Value,Date,IndicatorCode
count,437864,491076,490882,491076,491076,491076
unique,6,240,8,277375,2099,33
top,EUR,WPR,SEX_FMLE,0 [0-0],2024-10-03T16:19:34.33+02:00,AIR_15
freq,119377,3554,165212,45469,71060,35530

In [28]:
df1.isnull()

,ParentLocationCode,SpatialDim,Dim1,Value,NumericValue,Date,IndicatorCode
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
491071,False,False,False,False,False,False,False
491072,False,False,False,False,False,False,False
491073,False,False,False,False,False,False,False
491074,False,False,False,False,False,False,False
491075,False,False,False,False,False,False,False

In [29]:
df1["ParentLocationCode"].isnull().value_counts()
# ParentLocationCode
# False    437864
# True      53212
# Name: count, dtype: int64
#--Tui định bỏ hết, tại đống này cỡ 10% mà mình có tận 500k, xử lí hơi khó

ParentLocationCode
False    437864
True      53212
Name: count, dtype: int64

In [35]:
df1.dropna(subset = ["ParentLocationCode"],axis = 0, inplace = True )
df1["ParentLocationCode"].isnull().value_counts()

ParentLocationCode
False    437670
Name: count, dtype: int64

In [31]:
df1["SpatialDim"].isnull().value_counts()

SpatialDim
False    437864
Name: count, dtype: int64

In [36]:
df1["Dim1"].isnull().value_counts()
# Dim1
# False    490882
# True        194
# Name: count, dtype: int64
#-- này chắc bỏ luôn quá :)))

Dim1
False    437670
Name: count, dtype: int64

In [33]:
df1.dropna(subset = ["Dim1"], axis = 0, inplace=True)
df1["Dim1"].isnull().value_counts()

Dim1
False    437670
Name: count, dtype: int64

In [14]:
df1["Value"].isnull().value_counts()
#Cột này trong lúc xử lí thì bỏ cột do nó được chuyển sang cột NumericValue rồi

Value
False    491076
Name: count, dtype: int64

In [41]:
df1.drop(columns= ["Value"], axis=1 , errors= "ignore", inplace=True)
df1.columns

Index(['ParentLocationCode', 'SpatialDim', 'Dim1', 'NumericValue', 'Date',
       'IndicatorCode'],
      dtype='object')

In [42]:
df1["NumericValue"].isnull().value_counts()
# NumericValue
# False    490896
# True        180
# Name: count, dtype: int64
#này tui định xử lí bằng mean()

NumericValue
False    437490
True        180
Name: count, dtype: int64

In [16]:
df1["Date"].isnull().value_counts()
#-- tui định đổi định dạng trc, còn ngày tháng thì chắc chia them dummy + bins

Date
False    491076
Name: count, dtype: int64

In [17]:
df1["IndicatorCode"].isnull().value_counts()
#-- file này ít indicator code thì group theo được , mấy file kia nhiều code thì làm sao

IndicatorCode
False    491076
Name: count, dtype: int64